server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    context-path: /

spring:
  datasource:
    password: tester
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: tester

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 596637222821-3nd5m3h4h8gs4ca2o05cumrsef0ib30f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
